"""Stand-ins for the two fixed report sections, so a clean clone can run.

Sections 2 and 10 of the deliverable are not generated from the portal -- they
are fixed PDFs supplied locally in ``assets/static/``. Those two files are
gitignored, and deliberately so: one carries the contractor's branding, a staff
email address and a customer-portal URL, and neither is ours to publish. The
consequence is that a fresh clone has no way to assemble a ten-section report.

This module closes that gap without committing anything. It writes two clearly
marked stand-in PDFs with the right filenames and plausible page counts, so the
full pipeline -- merge order, page arithmetic, watermarking, validation -- can
be exercised from a clean checkout.

The stand-ins say what they are, on every page. That is the whole design: a
substituted section must be impossible to mistake for the real one in a
deliverable, so it is labelled in the text layer where validation and a reader
both see it. Anything assembled from these is a demonstration of the machinery,
not a report anyone may send.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

# Named in the text layer of every generated page, and asserted on by the
# tests, so a stand-in can always be told from the real document.
MARKER = "SYNTHETIC STAND-IN -- NOT THE REAL SECTION"

# filename -> (title, pages). The page counts match the real documents so the
# assembled length is representative.
STAND_INS: dict[str, tuple[str, int]] = {
    "ESA Table of Contents.pdf": ("ESA Table of Contents", 1),
    "TEGGPro View Customer Instructions.pdf": ("TEGGPro View Customer Instructions", 1),
}


@dataclass
class Written:
    """What was produced, and what was left alone."""

    created: list[Path]
    skipped: list[Path]

    def __str__(self) -> str:
        parts = []
        if self.created:
            parts.append(f"created {len(self.created)} stand-in(s)")
        if self.skipped:
            parts.append(f"left {len(self.skipped)} existing file(s) alone")
        return "; ".join(parts) or "nothing to do"


def _page(title: str, page: int, total: int) -> bytes:
    from reportlab.lib.pagesizes import LETTER
    from reportlab.pdfgen import canvas as pdfcanvas
    import io

    buffer = io.BytesIO()
    pdf = pdfcanvas.Canvas(buffer, pagesize=LETTER)
    width, height = LETTER
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawCentredString(width / 2, height - 100, title)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawCentredString(width / 2, height - 140, MARKER)
    pdf.setFont("Helvetica", 10)
    for offset, line in enumerate(
        (
            "This page was generated by tegg.mockassets so that a clean clone",
            "can run the controlled mock end to end. The real section is",
            "supplied locally and is not committed to this repository.",
            "",
            "A report assembled with this page in it must not be sent.",
        )
    ):
        pdf.drawCentredString(width / 2, height - 180 - offset * 16, line)
    pdf.setFont("Helvetica", 9)
    pdf.drawCentredString(width / 2, 60, f"Page {page} of {total}")
    pdf.showPage()
    pdf.save()
    return buffer.getvalue()


def write(destination: Path, *, overwrite: bool = False) -> Written:
    """Write any missing stand-in into ``destination``.

    An existing file is never replaced unless ``overwrite`` is asked for, so
    running this in a checkout that already holds the real assets cannot
    destroy them.
    """
    from pypdf import PdfWriter, PdfReader
    import io

    destination = Path(destination)
    destination.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []
    skipped: list[Path] = []

    for name, (title, pages) in STAND_INS.items():
        path = destination / name
        if path.exists() and not overwrite:
            skipped.append(path)
            continue
        writer = PdfWriter()
        for page in range(1, pages + 1):
            writer.append(PdfReader(io.BytesIO(_page(title, page, pages))))
        with path.open("wb") as handle:
            writer.write(handle)
        created.append(path)

    return Written(created=created, skipped=skipped)


def is_stand_in(path: Path) -> bool:
    """Whether this file is one of ours rather than the real section."""
    from pypdf import PdfReader

    try:
        reader = PdfReader(str(path))
        text = " ".join((p.extract_text() or "") for p in reader.pages[:2])
    except Exception:
        return False
    return MARKER.lower() in text.lower()
