"""Artifact naming, in one place so the convention cannot drift.

Two kinds of name matter:

  * the per-section source file, e.g. ``EquipmentInventoryShortForm.pdf``. That
    is owned by :mod:`tegg.canonical`, because the name is what classifies the
    document.
  * the assembled deliverable, e.g.
    ``DRAFT - TEGG_Atlas_Capital_The_Factory_2025-07-08.pdf``. That is owned
    here.

The deliverable name is the part a customer sees and the part an auditor reads,
so it is generated by one function and checked by another. ``DRAFT - `` is not
cosmetic: its presence or absence is the claim being made about whether the
report has been signed off, so :func:`check` verifies the prefix agrees with
whether the report is actually final.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .draft import FILENAME_PREFIX

PREFIX = "TEGG"
DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

# Everything that is not safe in a filename on Windows, macOS and Linux alike.
_UNSAFE = re.compile(r"[^A-Za-z0-9]+")


def token(value: str) -> str:
    """Reduce one name component to underscore-joined alphanumerics."""
    return _UNSAFE.sub("_", str(value)).strip("_")


def deliverable_name(
    customer: str,
    site: str,
    visit_date: str,
    *,
    draft: bool = True,
    suffix: str = "",
) -> str:
    """The filename for an assembled ESA report.

    ``draft`` defaults to True because a report is a draft until a human has
    signed the certificate. Producing a non-draft name is a deliberate act.
    """
    if not DATE.match(str(visit_date)):
        raise ValueError(
            f"visit_date must be YYYY-MM-DD, got {visit_date!r}. The date is part "
            "of the deliverable name and a wrong one misfiles the report."
        )
    parts = [PREFIX, token(customer), token(site), str(visit_date)]
    if suffix:
        parts.append(token(suffix))
    name = "_".join(p for p in parts if p) + ".pdf"
    return f"{FILENAME_PREFIX}{name}" if draft else name


@dataclass
class NameCheck:
    """Whether a filename follows the convention, and why not if it does not."""

    name: str
    ok: bool
    problems: list[str]
    is_draft: bool = False
    customer: str = ""
    site: str = ""
    visit_date: str = ""

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "ok": self.ok,
            "problems": list(self.problems),
            "is_draft": self.is_draft,
            "customer": self.customer,
            "site": self.site,
            "visit_date": self.visit_date,
        }


def check(
    name: str | Path,
    *,
    customer: str = "",
    site: str = "",
    visit_date: str = "",
    expect_draft: bool | None = None,
) -> NameCheck:
    """Verify a deliverable filename against the convention and the job.

    ``expect_draft`` is the honesty check: pass True when the report still has
    outstanding human review, and a name lacking ``DRAFT - `` is reported as a
    problem rather than accepted.
    """
    name = Path(name).name
    problems: list[str] = []

    is_draft = name.startswith(FILENAME_PREFIX)
    stem = name[len(FILENAME_PREFIX):] if is_draft else name

    if not stem.lower().endswith(".pdf"):
        problems.append(f"{name!r} does not end in .pdf")
    stem = stem[:-4] if stem.lower().endswith(".pdf") else stem

    fields = stem.split("_")
    if not fields or fields[0] != PREFIX:
        problems.append(f"{name!r} does not start with {PREFIX}_")

    found_date = ""
    for field in fields:
        if DATE.match(field):
            found_date = field
            break
    if not found_date:
        problems.append(f"{name!r} carries no YYYY-MM-DD visit date")
    elif visit_date and found_date != visit_date:
        problems.append(
            f"{name!r} carries the date {found_date}, but the job's visit date "
            f"is {visit_date}"
        )

    if customer and token(customer) not in stem:
        problems.append(f"{name!r} does not name the customer {customer!r}")
    if site and token(site) not in stem:
        problems.append(f"{name!r} does not name the site {site!r}")

    if expect_draft is True and not is_draft:
        problems.append(
            f"{name!r} is not marked {FILENAME_PREFIX.strip()} but the report "
            "still has outstanding human review"
        )
    if expect_draft is False and is_draft:
        problems.append(
            f"{name!r} is marked a draft but the report was declared final"
        )

    return NameCheck(
        name=name,
        ok=not problems,
        problems=problems,
        is_draft=is_draft,
        customer=customer,
        site=site,
        visit_date=found_date,
    )
