# TEGG Report Tool - build one site visit's report package.
#
# Double-click Run Report.bat.
#
# It asks you nine questions first, then reads the visit from TEGG, produces
# the eight documents in the package, and writes an email draft for you to
# check and send.
#
# It only ever reads from TEGG. It never submits anything, approves anything,
# uploads anything, or changes a record. It writes an email DRAFT and does not
# send it -- you press Send yourself, after reading it.

$ErrorActionPreference = 'Continue'

$Here = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $Here 'TEGG-Common.ps1')

if (-not (Test-ToolInstalled -Root $Here)) {
    Write-Say 'This tool has not been set up on this PC yet.'
    Write-Say ''
    Write-Say 'Double-click  Setup.bat  first. It only needs doing once.'
    Complete-Script 4
}

if (-not (Set-TeggCredentialEnvironment)) {
    Write-Say 'Your TEGG sign-in is not saved on this PC.'
    Write-Say ''
    Write-Say 'Double-click  Setup.bat  and enter it when asked.'
    Complete-Script 4
}

# A site visit may be named as the first argument -- normally by dropping
# nothing at all, in which case the tool picks the most recently completed one
# and says which it chose.
$passthrough = @($args)

# "Run Report.bat --run-id <id>" carries on a run that stopped partway. It is
# a different verb -- resume, not run -- because starting a new run with an
# existing id would fetch everything again.
$resumeId = ''
for ($i = 0; $i -lt $passthrough.Count; $i++) {
    if ("$($passthrough[$i])" -eq '--run-id' -and ($i + 1) -lt $passthrough.Count) {
        $resumeId = "$($passthrough[$i + 1])"
        break
    }
}

if ($resumeId) {
    $toolArgs = @('resume', '--run-id', $resumeId)
    $passthrough = @($passthrough | Where-Object { "$_" -ne '--run-id' -and "$_" -ne $resumeId })
} else {
    $toolArgs = @('run', 'visit-findings')
    if ($passthrough.Count -gt 0 -and $passthrough[0] -and -not ("$($passthrough[0])".StartsWith('-'))) {
        $toolArgs += '--site-visit'
        $toolArgs += "$($passthrough[0])"
        $passthrough = @($passthrough | Select-Object -Skip 1)
    }
}
if (Test-Path -LiteralPath (Join-Path $Here 'config\ratecard.yaml')) {
    $toolArgs += '--rate-card'
    $toolArgs += 'config/ratecard.yaml'
}
foreach ($extra in $passthrough) { $toolArgs += "$extra" }

Write-Say 'This tool will ask you about the report first, then read TEGG.'
Write-Say ''
Write-Say 'Answer the questions as they appear. Nothing is sent to TEGG until'
Write-Say 'you confirm them, and you can stop at any point with Ctrl+C.'
Write-Say ''
Write-Say 'After that it takes about four minutes: six reports have to be'
Write-Say 'generated by TEGG one at a time, and the certificate fetched'
Write-Say 'separately. You can leave it running.'
Write-Say ''

$code = 0
Push-Location -LiteralPath $Here
try {
    & (Get-VenvTool -Root $Here) @toolArgs
    $code = $LASTEXITCODE
} finally {
    Pop-Location
    # The sign-in existed only inside this window, and not past this line.
    Clear-TeggCredentialEnvironment
}

Write-Say ''
switch ($code) {
    0 {
        Write-Say 'Done. All eight documents were produced.'
        $latest = Get-LatestRunFolder -Root $Here
        if ($latest) {
            $documents = Join-Path $latest.FullName 'documents'
            $email     = Join-Path $latest.FullName 'email'
            $review    = Join-Path $latest.FullName 'review\review.md'

            Write-Say ''
            Write-Say 'Everything is here:'
            Write-Say ('  ' + $latest.FullName)
            if (Test-Path -LiteralPath $documents) {
                Write-Say ''
                Write-Say '  documents\   the eight documents for the customer'
                Get-ChildItem -LiteralPath $documents -Filter *.pdf -ErrorAction SilentlyContinue |
                    ForEach-Object { Write-Say ('                 ' + $_.Name) }
            }
            if (Test-Path -LiteralPath $review) {
                Write-Say '  review\      what was found, and what it is worth - READ THIS'
            }
            if (Test-Path -LiteralPath $email) {
                Write-Say '  email\       draft.eml - the email, NOT sent'
                Write-Say ''
                Write-Say 'The email has NOT been sent. To send it: open  email\draft.eml,'
                Write-Say 'read it, check the recipient and the attachments, then press Send'
                Write-Say 'yourself. "HOW TO SEND.txt" in that folder says the same thing.'
            }
            Write-Say ''
            Write-Say 'Opening the folder for you...'
            Start-Process -FilePath 'explorer.exe' -ArgumentList ('"' + $latest.FullName + '"') -ErrorAction SilentlyContinue
        }
    }
    1 { Write-Say 'It could not finish. Nothing in TEGG was changed and no email was sent.'
        Write-Say 'See TROUBLESHOOTING.txt.' }
    2 { Write-Say 'That command was not understood. Nothing was attempted.' }
    3 { Write-Say 'It stopped and needs a person.'
        Write-Say ''
        Write-Say 'Read the "human action required" lines above - they say what is needed.'
        Write-Say 'If it says fewer than eight documents were produced, that is deliberate:'
        Write-Say 'a part-finished package is never treated as finished, and nothing was'
        Write-Say 'emailed. The lines above name which report did not come back and why.'
        Write-Say ''
        Write-Say 'Nothing in TEGG was changed, and you can safely run this again -'
        Write-Say 'documents that already arrived are not fetched twice.'
        $latest = Get-LatestRunFolder -Root $Here
        if ($latest) {
            Write-Say ''
            Write-Say 'To carry on from where it stopped, without re-answering the'
            Write-Say 'questions or re-fetching what already arrived, run this:'
            Write-Say ('  Run Report.bat --run-id ' + $latest.Name)
        }
    }
    4 { Write-Say 'It did not start: something about this PC or its settings is not ready.'
        Write-Say 'Double-click  Check Setup.bat  to see what.' }
    default { Write-Say ('Finished with code ' + $code + '.') }
}
Complete-Script $code
